spring.application.name=petlog

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/petlog
spring.datasource.username=root
spring.datasource.password=test1234

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
mybatis.mapper-locations=classpath:/mappers/**/*.xml

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=msubi0831@gmail.com
spring.mail.password=lpxvmwydjclpocrg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# DOG, CAT api key
animal.dog-api-key=live_W2SkqsJAk4XwmdNO88MLplbTQUBYuQkBEsKCuy94vTfdGsoe2c73QQ0tK5bQOOlp
animal.cat-api-key=live_cowDcOgZYiKDeTCzuF60quc968NHAsL2e0G1qjzWvnPXVs1lxu0isy5svSIciSTe

mybatis.configuration.map-underscore-to-camel-case=true

# fileSize
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=300MB


file.upload-dir=uploads/review

file.base-url=http://localhost:8080


# ?? ??? ??? ?
kakao.rest.key=${KAKAO_REST_KEY}
# ????? ??? ?
public-data.service.key=${PUBLIC_DATA_KEY}



# =========================
# OAuth ??
# =========================

# Kakao
custom.property.kakao-client-id=${KAKAO_REST_KEY}
custom.property.kakao-redirect-uri=http://localhost:8080/user/login/kakao

# Naver
custom.property.naver-client-id=${NAVER_CLIENT_ID}
custom.property.naver-client-secret=${NAVER_CLIENT_SECRET}
custom.property.naver-redirect-uri=http://localhost:8080/user/login/naver


google.client.id=${GOOGLE_CLIENT_ID}
google.client.secret=${GOOGLE_CLIENT_SECRET}
google.redirect.uri=http://localhost:8080/user/login/google/callback